"""
QuantAI Professional v5
Trade Engine

Historical trade execution engine used by:
    - BacktestEngine
    - WalkForwardEngine
    - Strategy

Responsibilities:
    - open positions
    - update open positions
    - calculate position size
    - apply slippage
    - calculate commissions
    - manage Stop Loss
    - manage Take Profit
    - manage Break-Even
    - manage Trailing Stop
    - close positions
    - maintain balance/equity
    - expose trade statistics

IMPORTANT:
This module does NOT decide the trading signal.
Signals are generated by src.strategy.

Exit logic:
    1. Existing SL/TP are checked first.
    2. Only after the candle survives the exit check,
       Break-Even / Trailing Stop may update the SL.
    3. The newly updated SL becomes active starting
       from the NEXT candle.

This prevents a newly moved SL from being triggered
retroactively by the same candle.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Any, List, Optional

import pandas as pd

from config.settings import (
    INITIAL_BALANCE,
    RISK_PERCENT,
    COMMISSION,
    SLIPPAGE,
    MAX_OPEN_POSITIONS,
)

from src.strategy import (
    SignalResult,
    generate_signal_result,
)

from src.risk_manager import (
    calculate_position_size,
)


# ============================================================
# ENUMS
# ============================================================


class PositionSide(str, Enum):
    LONG = "BUY"
    SHORT = "SELL"


class PositionStatus(str, Enum):
    OPEN = "OPEN"
    CLOSED = "CLOSED"


class CloseReason(str, Enum):
    TAKE_PROFIT = "TAKE_PROFIT"
    STOP_LOSS = "STOP_LOSS"
    TRAILING_STOP = "TRAILING_STOP"
    BREAK_EVEN = "BREAK_EVEN"
    MANUAL = "MANUAL"
    END_OF_BACKTEST = "END_OF_BACKTEST"


# ============================================================
# POSITION
# ============================================================


@dataclass
class Position:
    """
    Represents one opened trade.
    """

    id: int

    side: PositionSide

    status: PositionStatus

    entry_time: object

    exit_time: Optional[object] = None

    entry_price: float = 0.0

    exit_price: float = 0.0

    stop_loss: float = 0.0

    take_profit: float = 0.0

    quantity: float = 0.0

    confidence: float = 0.0

    reason_open: List[str] = field(default_factory=list)

    reason_close: CloseReason = CloseReason.MANUAL

    commission: float = 0.0

    gross_profit: float = 0.0

    net_profit: float = 0.0

    balance_after_close: float = 0.0

    max_profit: float = 0.0

    max_drawdown: float = 0.0

    bars_open: int = 0

    # Track whether protective mechanisms have already moved.
    break_even_activated: bool = False
    trailing_activated: bool = False


# ============================================================
# TRADE ENGINE
# ============================================================


class TradeEngine:
    """
    Historical trade execution engine.

    The engine is intentionally independent from the strategy
    decision logic.

    Strategy:
        generates BUY / SELL / HOLD

    TradeEngine:
        executes and manages the resulting position
    """

    def __init__(self) -> None:

        self.initial_balance = float(
            INITIAL_BALANCE
        )

        self.balance = float(
            INITIAL_BALANCE
        )

        self.equity = float(
            INITIAL_BALANCE
        )

        self.positions: List[Position] = []

        self.closed_positions: List[Position] = []

        self.position_counter = 0

    # ========================================================
    # ENGINE HELPERS
    # ========================================================

    def next_position_id(self) -> int:
        """
        Generate the next position ID.
        """

        self.position_counter += 1

        return self.position_counter

    # --------------------------------------------------------

    def can_open_position(self) -> bool:
        """
        Check maximum simultaneous position limit.
        """

        return (
            len(self.positions)
            < MAX_OPEN_POSITIONS
        )

    # --------------------------------------------------------

    def get_open_positions(self) -> List[Position]:
        """
        Return currently open positions.
        """

        return [
            position
            for position in self.positions
            if position.status
            == PositionStatus.OPEN
        ]

    # ========================================================
    # COMMISSION
    # ========================================================

    def calculate_commission(
        self,
        quantity: float,
        price: float,
    ) -> float:
        """
        Calculate trading commission.
        """

        return (
            float(quantity)
            * float(price)
            * float(COMMISSION)
        )

    # ========================================================
    # SLIPPAGE
    # ========================================================

    def apply_slippage(
        self,
        side: PositionSide,
        price: float,
    ) -> float:
        """
        Apply configured slippage.

        BUY:
            price increases

        SELL:
            price decreases
        """

        price = float(price)

        if side == PositionSide.LONG:

            return price * (
                1.0 + float(SLIPPAGE)
            )

        return price * (
            1.0 - float(SLIPPAGE)
        )

    # ========================================================
    # OPEN POSITION
    # ========================================================

    def open_position(
        self,
        candle: Any,
        signal: SignalResult,
    ) -> bool:
        """
        Open a new position from a Strategy signal.
        """

        if not self.can_open_position():
            return False

        side = PositionSide(
            signal.signal
        )

        entry_price = self.apply_slippage(
            side,
            signal.entry,
        )

        stop_loss = float(
            signal.stop_loss
        )

        take_profit = float(
            signal.take_profit
        )

        # ----------------------------------------------------
        # Basic protective-level validation
        # ----------------------------------------------------

        if side == PositionSide.LONG:

            if stop_loss >= entry_price:
                return False

            if take_profit <= entry_price:
                return False

        else:

            if stop_loss <= entry_price:
                return False

            if take_profit >= entry_price:
                return False

        # ----------------------------------------------------
        # Position size
        # ----------------------------------------------------

        quantity = calculate_position_size(
            balance=self.balance,
            risk_percent=RISK_PERCENT,
            entry_price=entry_price,
            stop_loss=stop_loss,
        )

        quantity = float(quantity)

        if quantity <= 0:
            return False

        # ----------------------------------------------------
        # Entry commission
        # ----------------------------------------------------

        commission = self.calculate_commission(
            quantity,
            entry_price,
        )

        # ----------------------------------------------------
        # Position
        # ----------------------------------------------------

        position = Position(
            id=self.next_position_id(),

            side=side,

            status=PositionStatus.OPEN,

            entry_time=candle["timestamp"],

            entry_price=round(
                entry_price,
                2,
            ),

            stop_loss=round(
                stop_loss,
                2,
            ),

            take_profit=round(
                take_profit,
                2,
            ),

            quantity=round(
                quantity,
                6,
            ),

            confidence=float(
                signal.confidence
            ),

            reason_open=list(
                signal.reasons
            ),

            commission=commission,
        )

        self.positions.append(
            position
        )

        return True

    # ========================================================
    # EXIT CHECK
    # ========================================================

    def _check_exit_conditions(
        self,
        position: Position,
        candle: Any,
    ) -> bool:
        """
        Check the SL/TP levels that were active BEFORE
        the current candle.

        Important:
        Break-Even and Trailing Stop are NOT modified here.

        This avoids retroactively applying a newly moved
        protective level to the same candle.
        """

        high = float(
            candle["high"]
        )

        low = float(
            candle["low"]
        )

        # ----------------------------------------------------
        # LONG
        # ----------------------------------------------------

        if position.side == PositionSide.LONG:

            stop_hit = (
                low
                <= position.stop_loss
            )

            take_profit_hit = (
                high
                >= position.take_profit
            )

            # Conservative assumption:
            # if both are touched inside the same candle,
            # assume Stop Loss happened first.
            if stop_hit:

                self.close_position(
                    position,
                    candle,
                    position.stop_loss,
                    CloseReason.STOP_LOSS,
                )

                return True

            if take_profit_hit:

                self.close_position(
                    position,
                    candle,
                    position.take_profit,
                    CloseReason.TAKE_PROFIT,
                )

                return True

        # ----------------------------------------------------
        # SHORT
        # ----------------------------------------------------

        else:

            stop_hit = (
                high
                >= position.stop_loss
            )

            take_profit_hit = (
                low
                <= position.take_profit
            )

            # Conservative assumption:
            # SL has priority if both are touched.
            if stop_hit:

                self.close_position(
                    position,
                    candle,
                    position.stop_loss,
                    CloseReason.STOP_LOSS,
                )

                return True

            if take_profit_hit:

                self.close_position(
                    position,
                    candle,
                    position.take_profit,
                    CloseReason.TAKE_PROFIT,
                )

                return True

        return False

    # ========================================================
    # BREAK-EVEN
    # ========================================================

    def _update_break_even(
        self,
        position: Position,
        high: float,
        low: float,
        atr: float,
    ) -> bool:
        """
        Move SL to entry after price moves by one ATR.

        The new SL becomes active on the NEXT candle.

        Returns:
            True if SL was changed.
        """

        if position.break_even_activated:
            return False

        if atr <= 0:
            return False

        # ----------------------------------------------------
        # LONG
        # ----------------------------------------------------

        if position.side == PositionSide.LONG:

            trigger = (
                position.entry_price
                + atr
            )

            if (
                high >= trigger
                and position.stop_loss
                < position.entry_price
            ):

                position.stop_loss = round(
                    position.entry_price,
                    2,
                )

                position.break_even_activated = True

                return True

        # ----------------------------------------------------
        # SHORT
        # ----------------------------------------------------

        else:

            trigger = (
                position.entry_price
                - atr
            )

            if (
                low <= trigger
                and position.stop_loss
                > position.entry_price
            ):

                position.stop_loss = round(
                    position.entry_price,
                    2,
                )

                position.break_even_activated = True

                return True

        return False

    # ========================================================
    # TRAILING STOP
    # ========================================================

    def _update_trailing_stop(
        self,
        position: Position,
        close: float,
        atr: float,
    ) -> bool:
        """
        Update trailing stop.

        The new SL becomes active on the NEXT candle.

        Returns:
            True if SL was changed.
        """

        if atr <= 0:
            return False

        trail_distance = (
            atr * 2.0
        )

        changed = False

        # ----------------------------------------------------
        # LONG
        # ----------------------------------------------------

        if position.side == PositionSide.LONG:

            new_stop = (
                close
                - trail_distance
            )

            # Never move a long SL downward.
            if new_stop > position.stop_loss:

                position.stop_loss = round(
                    new_stop,
                    2,
                )

                position.trailing_activated = True

                changed = True

        # ----------------------------------------------------
        # SHORT
        # ----------------------------------------------------

        else:

            new_stop = (
                close
                + trail_distance
            )

            # Never move a short SL upward.
            if new_stop < position.stop_loss:

                position.stop_loss = round(
                    new_stop,
                    2,
                )

                position.trailing_activated = True

                changed = True

        return changed

    # ========================================================
    # POSITION UPDATE
    # ========================================================

    def update_position(
        self,
        position: Position,
        candle: Any,
    ) -> bool:
        """
        Update one open position.

        Processing order:

            1. increment bars
            2. calculate floating PnL
            3. check existing SL
            4. check existing TP
            5. update Break-Even
            6. update Trailing Stop

        Protective levels changed in steps 5-6 are active
        only from the next candle.
        """

        position.bars_open += 1

        high = float(
            candle["high"]
        )

        low = float(
            candle["low"]
        )

        close = float(
            candle["close"]
        )

        atr = float(
            candle.get("atr", 0.0)
        )

        # ====================================================
        # FLOATING PROFIT / DRAWDOWN
        # ====================================================

        if position.side == PositionSide.LONG:

            floating = (
                close
                - position.entry_price
            ) * position.quantity

        else:

            floating = (
                position.entry_price
                - close
            ) * position.quantity

        position.max_profit = max(
            position.max_profit,
            floating,
        )

        position.max_drawdown = min(
            position.max_drawdown,
            floating,
        )

        # ====================================================
        # 1. CHECK EXISTING EXIT LEVELS
        # ====================================================

        if self._check_exit_conditions(
            position,
            candle,
        ):

            return True

        # Position could have been closed above.
        if position.status != PositionStatus.OPEN:

            return True

        # ====================================================
        # 2. BREAK-EVEN
        # ====================================================

        self._update_break_even(
            position,
            high,
            low,
            atr,
        )

        # ====================================================
        # 3. TRAILING STOP
        # ====================================================

        self._update_trailing_stop(
            position,
            close,
            atr,
        )

        return False

    # ========================================================
    # CLOSE POSITION
    # ========================================================

    def close_position(
        self,
        position: Position,
        candle: Any,
        exit_price: float,
        reason: CloseReason,
    ) -> None:
        """
        Close an open position.

        Slippage is applied to the requested exit level.

        Therefore:
            LONG SL exit can appear above the recorded SL
            SHORT SL exit can appear below the recorded SL

        This is expected because of slippage.
        """

        if position.status != PositionStatus.OPEN:
            return

        # ====================================================
        # EXIT PRICE
        # ====================================================

        requested_exit_price = float(
            exit_price
        )

        executed_exit_price = (
            self.apply_slippage(
                position.side,
                requested_exit_price,
            )
        )

        position.exit_time = (
            candle["timestamp"]
        )

        position.exit_price = round(
            executed_exit_price,
            2,
        )

        position.reason_close = reason

        position.status = (
            PositionStatus.CLOSED
        )

        # ====================================================
        # GROSS PROFIT
        # ====================================================

        if position.side == PositionSide.LONG:

            gross_profit = (
                executed_exit_price
                - position.entry_price
            ) * position.quantity

        else:

            gross_profit = (
                position.entry_price
                - executed_exit_price
            ) * position.quantity

        position.gross_profit = round(
            gross_profit,
            2,
        )

        # ====================================================
        # EXIT COMMISSION
        # ====================================================

        exit_commission = (
            self.calculate_commission(
                position.quantity,
                executed_exit_price,
            )
        )

        position.commission += (
            exit_commission
        )

        position.commission = round(
            position.commission,
            4,
        )

        # ====================================================
        # NET PROFIT
        # ====================================================

        position.net_profit = round(
            position.gross_profit
            - position.commission,
            2,
        )

        # ====================================================
        # BALANCE
        # ====================================================

        self.balance = round(
            self.balance
            + position.net_profit,
            2,
        )

        position.balance_after_close = (
            self.balance
        )

        self.equity = self.balance

        # ====================================================
        # ARCHIVE
        # ====================================================

        self.closed_positions.append(
            position
        )

        if position in self.positions:

            self.positions.remove(
                position
            )

        # ====================================================
        # DEBUG
        # ====================================================

        print(
            f"[{position.id}] "
            f"{position.side.value} "
            f"{position.reason_close.value} "
            f"PnL={position.net_profit:.2f}$ "
            f"Balance={self.balance:.2f}$"
        )

    # ========================================================
    # MAIN ENGINE LOOP
    # ========================================================

    def run(
        self,
        df: pd.DataFrame,
    ) -> pd.DataFrame:
        """
        Run historical backtest.

        Strategy signals are evaluated using historical data
        up to the current candle.

        Existing positions are updated BEFORE a new signal
        is generated.
        """

        if not isinstance(
            df,
            pd.DataFrame,
        ):

            raise TypeError(
                "TradeEngine.run() requires "
                "a pandas DataFrame."
            )

        if df.empty:

            return self.to_dataframe()

        # Indicators require historical warm-up.
        start_index = 250

        if len(df) <= start_index:

            return self.to_dataframe()

        # ====================================================
        # HISTORICAL LOOP
        # ====================================================

        for i in range(
            start_index,
            len(df),
        ):

            history = df.iloc[
                : i + 1
            ]

            candle = (
                history.iloc[-1]
            )

            # ------------------------------------------------
            # UPDATE EXISTING POSITIONS
            # ------------------------------------------------

            for position in (
                self.get_open_positions()[:]
            ):

                self.update_position(
                    position,
                    candle,
                )

            # ------------------------------------------------
            # MAXIMUM POSITIONS
            # ------------------------------------------------

            if not self.can_open_position():

                continue

            # ------------------------------------------------
            # STRATEGY
            # ------------------------------------------------

            signal = (
                generate_signal_result(
                    history
                )
            )

            if signal.signal == "HOLD":

                continue

            # ------------------------------------------------
            # OPEN POSITION
            # ------------------------------------------------

            self.open_position(
                candle,
                signal,
            )

        # ====================================================
        # CLOSE REMAINING POSITIONS
        # ====================================================

        open_positions = (
            self.get_open_positions()[:]
        )

        if open_positions:

            last_candle = (
                df.iloc[-1]
            )

            for position in open_positions:

                self.close_position(
                    position,
                    last_candle,
                    float(
                        last_candle["close"]
                    ),
                    CloseReason.END_OF_BACKTEST,
                )

        return self.to_dataframe()

    # ========================================================
    # DATAFRAME EXPORT
    # ========================================================

    def to_dataframe(
        self,
    ) -> pd.DataFrame:
        """
        Convert closed positions into a DataFrame.
        """

        rows = []

        for trade in (
            self.closed_positions
        ):

            rows.append(
                {
                    "id": trade.id,

                    "side":
                        trade.side.value,

                    "entry_time":
                        trade.entry_time,

                    "exit_time":
                        trade.exit_time,

                    "entry":
                        round(
                            trade.entry_price,
                            2,
                        ),

                    "exit":
                        round(
                            trade.exit_price,
                            2,
                        ),

                    "stop_loss":
                        round(
                            trade.stop_loss,
                            2,
                        ),

                    "take_profit":
                        round(
                            trade.take_profit,
                            2,
                        ),

                    "quantity":
                        round(
                            trade.quantity,
                            6,
                        ),

                    "confidence":
                        round(
                            trade.confidence,
                            2,
                        ),

                    "bars":
                        trade.bars_open,

                    "gross_profit":
                        round(
                            trade.gross_profit,
                            2,
                        ),

                    "commission":
                        round(
                            trade.commission,
                            4,
                        ),

                    "net_profit":
                        round(
                            trade.net_profit,
                            2,
                        ),

                    "balance":
                        round(
                            trade.balance_after_close,
                            2,
                        ),

                    "close_reason":
                        trade.reason_close.value,
                }
            )

        # ----------------------------------------------------
        # Empty DataFrame
        # ----------------------------------------------------

        if not rows:

            return pd.DataFrame(
                columns=[
                    "id",
                    "side",
                    "entry_time",
                    "exit_time",
                    "entry",
                    "exit",
                    "stop_loss",
                    "take_profit",
                    "quantity",
                    "confidence",
                    "bars",
                    "gross_profit",
                    "commission",
                    "net_profit",
                    "balance",
                    "close_reason",
                ]
            )

        return pd.DataFrame(
            rows
        )

    # ========================================================
    # STATISTICS
    # ========================================================

    @property
    def total_trades(self) -> int:
        """
        Total number of closed trades.
        """

        return len(
            self.closed_positions
        )

    # --------------------------------------------------------

    @property
    def winning_trades(self) -> int:
        """
        Number of profitable trades.
        """

        return sum(
            1
            for position
            in self.closed_positions
            if position.net_profit > 0
        )

    # --------------------------------------------------------

    @property
    def losing_trades(self) -> int:
        """
        Number of losing or flat trades.
        """

        return sum(
            1
            for position
            in self.closed_positions
            if position.net_profit <= 0
        )

    # --------------------------------------------------------

    @property
    def total_profit(self) -> float:
        """
        Total net profit.
        """

        return round(
            sum(
                position.net_profit
                for position
                in self.closed_positions
            ),
            2,
        )

    # --------------------------------------------------------

    @property
    def win_rate(self) -> float:
        """
        Winning trades percentage.
        """

        if self.total_trades == 0:

            return 0.0

        return round(
            (
                self.winning_trades
                / self.total_trades
            )
            * 100.0,
            2,
        )


# ============================================================
# PUBLIC RUNNER
# ============================================================


def run_trade_engine(
    df: pd.DataFrame,
) -> pd.DataFrame:
    """
    Convenience wrapper for TradeEngine.
    """

    engine = TradeEngine()

    trades = engine.run(
        df
    )

    print()

    print(
        "=" * 60
    )

    print(
        "TRADE ENGINE REPORT"
    )

    print(
        "=" * 60
    )

    print(
        f"Initial Balance : "
        f"{engine.initial_balance:.2f}"
    )

    print(
        f"Final Balance   : "
        f"{engine.balance:.2f}"
    )

    print(
        f"Net Profit      : "
        f"{engine.total_profit:.2f}"
    )

    print(
        f"Trades          : "
        f"{engine.total_trades}"
    )

    print(
        f"Wins            : "
        f"{engine.winning_trades}"
    )

    print(
        f"Losses          : "
        f"{engine.losing_trades}"
    )

    print(
        f"Win Rate        : "
        f"{engine.win_rate:.2f}%"
    )

    print(
        "=" * 60
    )

    return trades


# ============================================================
# EXPORTS
# ============================================================


__all__ = [
    "Position",
    "PositionSide",
    "PositionStatus",
    "CloseReason",
    "TradeEngine",
    "run_trade_engine",
]
